### ISSUE TITLE
Project does not compile on Visual Studio 16.7.3

### ISSUE THREAD

**Issue by laoo** [johnwbyrd/llvm-mos#4]
This assertion
https://github.com/johnwbyrd/llvm-mos/blob/e9f9a775899a920403280186c796be757a0cff8c/llvm/include/llvm/Support/type_traits.h#L179-L182
Fires on Visual Studio 16.7.3.

The problem has been already reported in [Visual Studio Developer Community Forum](https://developercommunity.visualstudio.com/content/problem/1162322/inconsistent-behavior-between-llvm-and-std-impleme.html).  There is a mention that it has been fixed in latest LLVM. Maybe rebasing to newer LLVM will fix the issue.

**Comment by johnwbyrd** [comment]
I consider that likely.  I'll give rebasing a shot.  If this succeeds, I would have to obviously ask you to rebase any of your work on latest.

**Comment by johnwbyrd** [comment]
I've done an experimental rebase, and apparently LLVM has changed plenty of high-level logic since the last rebase I did.  This bug must be solved but it will take a few days to sort through all the internal API changes and make the right choices.

**Comment by johnwbyrd** [comment]
This is why the cleanup is complicated: https://reviews.llvm.org/D85165

**Comment by laoo** [comment]
That's some heavy patch but obviously it would not be wise to postpone any rebasing with head of llvm repository. It will surely pay off.

**Comment by johnwbyrd** [comment]
Please check out and review 216efa94536c0e86cf2c123be817cc583e955b83 .  A bunch of rebasing was required to integrate all the changes from the most recent tree, but it seems to pass build and smoke test on my machines.

**Comment by laoo** [comment]
Newest version compiles flawlessly.
